# Generated by Django 3.1.2 on 2023-02-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=9)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=40)),
                ('penerbit', models.CharField(max_length=40)),
                ('jumlah_buku', models.IntegerField(null=True)),
                ('cover', models.ImageField(null=True, upload_to='cover/')),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('kelompok', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.kelompok')),
            ],
        ),
    ]
